project_id = "ntpaixfucjcxkntskcka"

[functions.admin-create-user]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.gmail-oauth]
verify_jwt = false

[functions.test-twilio]
verify_jwt = false