// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntpaixfucjcxkntskcka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50cGFpeGZ1Y2pjeGtudHNrY2thIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyNTI3NjMsImV4cCI6MjA4MDgyODc2M30.Y1-esIV0XB6tXPC_njMeyNJvXFwojgDW71KB2ftUdnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});